trigger:
  - develop
  - main

pool:
  vmImage: 'ubuntu-latest'

# Terraform

jobs:
- job: terraform
  steps:

  - task: CopyFiles@2
    displayName: 'Copy Terraform files to artifacts'
    inputs:
      SourceFolder: Scripts/Terraform
      TargetFolder: '$(Build.ArtifactStagingDirectory)/Terraform'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Terraform Artifacts'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/Terraform'
      ArtifactName: 'Terraform'
      publishLocation: 'Container'

# App

- job: nodejs
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'

  - task: CopyFiles@2
    inputs:
      SourceFolder: 3proj-backend
      TargetFolder: '$(Build.ArtifactStagingDirectory)/backend'

  - task: PublishBuildArtifacts@1
    inputs: 
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/backend'
      ArtifactName: 'backend'
      publishLocation: 'Container'

- job: backend
  steps:
  - task: Npm@1
    inputs:
      command: 'install'
      workingDir: '3proj/3proj-backend'