trigger:
  - develop
  - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: terraform
  steps:

  - task: CopyFiles@2
    displayName: 'Copy Terraform files to artifacts'
    inputs:
      SourceFolder: Scripts/Terraform
      TargetFolder: '$(Build.ArtifactStagingDirectory)/Terraform'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Terraform Artifacts'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/Terraform'
      ArtifactName: 'Terraform'
      publishLocation: 'Container'