trigger:
  - develop
  - main

pool:
  vmImage: 'ubuntu-latest'

# Terraform (Without documentation)

jobs:
- job: Terraform
  steps:

  - task: CopyFiles@2
    displayName: 'Copy Terraform files to artifacts'
    inputs:
      SourceFolder: 'Scripts/Terraform'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/Terraform'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Terraform Artifacts'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/Terraform'
      ArtifactName: 'Terraform'
      publishLocation: 'Container'

## Install prerequisite for App (NodeJS)

- job: 'Install_Nodejs'
  steps:
  - task: NodeTool@0
    displayName: 'Install Nodejs'
    inputs:
      versionSpec: '16.x'

# App - Backend : Create Artefact

- job: Backend
  steps:
  # - task: Npm@1
  #   displayName: 'Install node modules'
  #   inputs:
  #     command: 'install'
  #     workingDir: '3proj-backend'

          # Restore cache.
  - task: Cache@2
    inputs:
      key: 'npm | "$(Agent.OS)" | 3proj-backend/package-lock.json'
      restoreKeys: |
        npm | "$(Agent.OS)"
      path: $(nodeModulesCache)
    displayName: Cache Node modules

# Create .env with secured variables

  - task: file-creator@6
    displayName: 'Create .env'
    inputs:
      filepath: '$(Build.ArtifactStagingDirectory)/Backend/.env'
      filecontent: |
        DB_CONNECTION_STRING = $(DB_CONNECTION_STRING)
        SECRET_TOKEN = $(SECRET_TOKEN)
        SECRET_TOKEN_DURATION = $(SECRET_TOKEN_DURATION)

  - task: CopyFiles@2
    displayName: 'Copy Backend files to artifacts'
    inputs:
      SourceFolder: '3proj-backend'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/Backend'
      
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Backend Artifacts'
    inputs: 
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/Backend'
      ArtifactName: 'Backend'
      publishLocation: 'Container'

# # App - Frontend : Create Artefact

# - job: Frontend
#   steps:
#   - task: Npm@1
#     displayName: 'Install node modules'
#     inputs:
#       command: 'install'
#       workingDir: '3proj-frontend'

#   - task: CopyFiles@2
#     displayName: 'Copy Frontend files to artifacts'
#     inputs:
#       SourceFolder: '3proj-frontend'
#       TargetFolder: '$(Build.ArtifactStagingDirectory)/Frontend'
      
#   - task: PublishBuildArtifacts@1
#     displayName: 'Publish Frontend Artifacts'
#     inputs: 
#       PathtoPublish: '$(Build.ArtifactStagingDirectory)/Frontend'
#       ArtifactName: 'Frontend'
#       publishLocation: 'Container'