trigger:
  - develop
  - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: terraform
  steps:
  - task: PublishBuildArtifacts@1
    displayName: 'Make Terraform Artifacts'
    inputs:
      PathtoPublish: 'Terraform'
      ArtifactName: 'Terraform'
      publishLocation: 'Container'