trigger:
  - develop
  - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: terraform
  steps:

  - task: CopyFiles@2
    displayName: 'Copy Terraform files to artifacts'
    inputs:
      SourceFolder: Scripts/Terraform
      TargetFolder: '$(Build.ArtifactStagingDirectory)/Terraform'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Terraform Artifacts'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/Terraform'
      ArtifactName: 'Terraform'
      publishLocation: 'Container'

# Node.js tool installer
# Finds or downloads and caches the specified version spec of Node.js and adds it to the PATH
- job: nodejs
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'

- job: backend
  steps:
  - task: Npm@1
    inputs:
      command: 'install'
      workingDir: '/3proj-backend'