trigger:
  - develop
  - main

pool:
  vmImage: 'ubuntu-latest'

# Terraform

jobs:
- job: Terraform
  steps:

  - task: CopyFiles@2
    displayName: 'Copy Terraform files to artifacts'
    inputs:
      SourceFolder: Scripts/Terraform
      TargetFolder: '$(Build.ArtifactStagingDirectory)/Terraform'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Terraform Artifacts'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/Terraform'
      ArtifactName: 'Terraform'
      publishLocation: 'Container'

# App

- job: Backend
  steps:
  - task: NodeTool@0
    displayName: 'Install Nodejs'
    inputs:
      versionSpec: '16.x'

  - task: CopyFiles@2
    displayName: 'Copy Backend files to artifacts'
    inputs:
      SourceFolder: 3proj-backend
      TargetFolder: '$(Build.ArtifactStagingDirectory)/Backend'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Backend Artifacts'
    inputs: 
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/Backend'
      ArtifactName: 'Backend'
      publishLocation: 'Container'

  - task: Npm@1
    displayName: 'npm install'
    inputs:
      command: 'install'
      workingDir: '$(Build.ArtifactStagingDirectory)/Backend'