trigger:
  - develop
  - main

pool:
  vmImage: 'ubuntu-latest'

# Terraform

jobs:
- job: Terraform
  steps:

  - task: CopyFiles@2
    displayName: 'Copy Terraform files to artifacts'
    inputs:
      SourceFolder: 'Scripts/Terraform'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/Terraform'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Terraform Artifacts'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/Terraform'
      ArtifactName: 'Terraform'
      publishLocation: 'Container'

# App - Backend

- job: Backend
  steps:
  - task: NodeTool@0
    displayName: 'Install Nodejs'
    inputs:
      versionSpec: '14.x'

  - task: Npm@1
    displayName: 'npm install'
    inputs:
      command: 'install'
      workingDir: '3proj-backend'

  - task: file-creator@6
    inputs:
      filepath: '$(Build.ArtifactStagingDirectory)/Backend/.env'
      filecontent: |
        SERVER_PORT = $(SERVER_PORT)
        DB_CONNECTION_STRING = $(DB_CONNECTION_STRING)
        SECRET_TOKEN = $(SECRET_TOKEN)
        SECRET_TOKEN_DURATION = $(SECRET_TOKEN_DURATION)

  - task: CopyFiles@2
    displayName: 'Copy Backend files to artifacts'
    inputs:
      SourceFolder: '3proj-backend'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/Backend'
      
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Backend Artifacts'
    inputs: 
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/Backend'
      ArtifactName: 'Backend'
      publishLocation: 'Container'